substitutions:
  _IMAGE_NAME: gcr.io/$PROJECT_ID/$REPO_NAME
steps: 
- name: "docker"
  args: ["build", "-t", "${_IMAGE_NAME}", "."]
 
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "${_IMAGE_NAME}"]

- name: "gcr.io/cloud-builders/kubectl"
  args: ["apply", "-f", "gke.yaml"]
